### ISSUE TITLE
Playing back cartridges with https data fails

### ISSUE THREAD

**Issue by paulspencerwilliams** [sonian/cartridge#1]
I've successfully used cartridge to record and playback plain http traffic. However, when I try to record and playback encrypted https traffic, (json in my case), data from the resultant playback is invalid - I believe encrypted. Certainly, the contents of the cartridge file is encrypted.

**Comment by leathekd** [comment]
@paulspencerwilliams I tried to reproduce this, both by going to some https destination on the web and by adapting the cartridge integration tests to use ssl.  Both appear to be working fine.  Could you elaborate on your setup and code?  It would be super helpful if you could reproduce against a publicly available website but I'm happy to try and help even if I cannot reproduce locally.

One thing to note regarding the contents of the cartridge file- it may be that you're seeing a base64 encoded stream.  Cartridge will b64-encode basically anything that isn't nil or a string.
